### ISSUE TITLE
no file size reduction 

### ISSUE THREAD

**Issue by MagicAndre1981** [itoleck/ETLSmasher#1]
thanks for the idea of the tool, but for me it doesn't work. I see no file size change, the only thing that reduces the file is to use `wpr -merge oldfile.etl newfile.etl -compress `. This reduces the size from 1.2 GB to 200MB

**Comment by itoleck** [comment]
Thanks, I was putting this off but had to track it down. 1 character fixed and it's working again.

**Comment by MagicAndre1981** [comment]
> 1 character fixed and it's working again.

confirmed that it works, only thing is that the filesize is 5MB larger compared to WPR. Any ideas how to diff both generated files?

**Comment by itoleck** [comment]
You can open each file in Wpa.exe and go to menu -> trace -> system configuration -> trace statistics and see how many and size of each provider's events and compare. An actual diff of the fifes would not work as they are binary and not necessarily in the same event order. Any differences would be that the Microsoft.Diagnostics.Tracing.TraceEvent package used by this app opens each event and if there is any issue with the event like missing information the event would be dropped. If you just need compression and do not care to remove providers or timeframe xperf would be better option but it's included here anyway.

**Comment by MagicAndre1981** [comment]
ok, I used EventStats view from Perfview to compare them and both show same event numbers. So your tool and xperf/wpr work same (when using -mergeonly flag with xperf/wpr, this is important to not add events from your current system to the ETL) only difference is that your files are 5MB larger. I'll keep your tool in mind when I need to remove providers
